Add yet another HORdec representation
ablab/HORmon pull request #4
Opened 2021-10-01 09:39 UTC by TanyaDvorkina

Forgot to add HOR decomposition representation that is needed for paper

2021-10-06 20:25 UTC, seryrzu requested changes

2021-10-06 20:25 UTC, seryrzu commented on src/hormon_extract_hors.py
>             mon_seq = hordec_c[-1][1]
Nit: in the future let's create a class that has clearly named fields. Otherwise it is unclear what `5` refers to in `hordec_c[-1][5]`
No action is required right now

2021-10-06 20:25 UTC, seryrzu commented on src/hormon_extract_hors.py
> +               hordec_c[-1][1] = collapse_name(revert_hor(mon_seq), mono_mp, hors[cur_hor_name]) + "'"
The name of the monomer might be a class that can have a method `.reverse()` that automatically either adds ' or removes it, so we don't need to worry about it in the external code. Especially if we decide to change ' to a different character later (or change the behavior of `.reverse()`

No action is required right now

2021-10-06 20:25 UTC, seryrzu commented on src/hormon_extract_hors.py
> +        hordec_c[-1][1] = collapse_name(revert_hor(mon_seq), mono_mp, hors[cur_hor_name]) + "'"
Code duplication with above, please reduce

2021-10-06 20:25 UTC, seryrzu commented on src/hormon_extract_hors.py
> +    hordec_c = collapse_hordec(copy.deepcopy(hordec), mono_mp, hors, False)
Please explicitly write that `revert=False`

2021-10-06 20:25 UTC, seryrzu commented on src/hormon_extract_hors.py
> +    with open(outfilename[:-len(".tsv")]+"_collapsed.tsv", "w") as fout:
- Please assign a filename to a variable.
- please use `from pathlib import Path` for paths as a modern way to deal with paths in python
- changing extensions is done automatically with pathlib. see https://stackoverflow.com/a/42288083

2021-10-06 20:25 UTC, seryrzu commented on src/hormon_extract_hors.py
> +           fout.write("\t".join(hordec_c[i]).replace("{","").replace("}", "") + "\n")
If speed is not an issue, you might use `print(..., file=fout)` that will automatically add `"\n"`. No need to change that though.

However, please break the code in several lines so it is easier to read and add a comment why these replaces are needed (ideally we need to have methods of classes that do that, but no need for that atm).

2021-10-06 20:25 UTC, seryrzu commented on src/hormon_extract_hors.py
> +    print("Collapsed HOR decomposition saved to", outfilename[:-len(".tsv")]+"_collapsed.tsv")
please reuse the filename from above

2021-10-06 20:25 UTC, seryrzu commented on src/hormon_extract_hors.py
> +    hordec_c = collapse_hordec(hordec, mono_mp, hors, revert)
if `revert == False` do we save the same thing twice?

Seem like code duplication? can we reduce?

2021-10-07 10:50 UTC, TanyaDvorkina commented on src/hormon_extract_hors.py
> +    with open(outfilename[:-len(".tsv")]+"_collapsed.tsv", "w") as fout:
Fixed it, but pathlib doesn't give opportunity to add arbitrary suffix ("_collapsed.tsv" - no, ".collapsed.tsv" - yes).  But for now it is Ok.

2021-10-07 11:10 UTC, TanyaDvorkina commented on src/hormon_extract_hors.py
> +           fout.write("\t".join(hordec_c[i]).replace("{","").replace("}", "") + "\n")
Oh! Thanks! It was from old representation!

2021-10-07 11:22 UTC, TanyaDvorkina commented on src/hormon_extract_hors.py
> +    hordec_c = collapse_hordec(hordec, mono_mp, hors, revert)
It is more run duplication, I fixed it, but I want to leave? saving twice two equal results to have the same set of files after each run.

2021-10-07 16:30 UTC, merged